local day = {
	{"Overall",
		{"Score Earned",1},
		{"Score Lost",1},
		{"Bullets Fired",1},
		{"Average Per Minute",1},
		{"Ammunation Sales ($)",1},
		{"Deaths",1},
		{"Money Gained",1},
		{"Money Transferred",1},
		{"Hours Accumulated",1},
		{"Jail Time Served",1},
		{"Wanted Points Earned",1},
		{"Hits of Drugs Taken",1},
		{"# of Store Robberies",1},
		{"# of Failed Store Robberies",1},
		{"# of Successfull Store Robberies",1},
		{"# of Player Robberies",1},
		{"# of Failed Player Robberies",1},
		{"# of Successfull Player Robberies",1},
		{"$ lost due to Robberies",1},
		{"$ gained from Store Robberies",1},
		{"Attempted Bank Robberies",1},
		{"Successfull Bank Robberies",1},
		{"# of crimes committed",1},
		{"$ Taxed Overall",1},
		{"Attempted Armored Deliveries",1},
		{"Successfull Armored Deliveries",1},
	},
	{"Law",
		{"Arrests",1},
		{"Jails",1},
		{"Assists",1},
		{"Bribes Accepted",1},
		{"$ from Bribes",1},
		{"Deaths",1},
		{"Bullets Fired",1},
		{"# of Crime Reports",1},
		{"Attempted Patrol Missions",1},
		{"Successfull Patrol Missions",1},
		{"Total # of Patrol Calls",1},
	},
	{"Civilians",
		{"Deaths",1},
		{"Money Gained",1},
		{"Bus Driver Routes Completed",1},
		{"# of Fish Caught",1},
		{"$ of Fish Caught",1},
		{"# of Fires put out",1},
		{"# of Truck Deliveries",1},
		{"# of flights Completed",1},
	},
	{"Criminals",
		{"Deaths",1},
		{"Turfs Taken",1},
		{"Deaths in LV",1},
		{"Wanted Points evaded",1},
		{"Bullets Fired",1},
	}

}

local week = {
	{"Overall",
		{"Score Earned",1},
		{"Score Lost",1},
		{"Bullets Fired",1},
		{"Average Per Minute",1},
		{"Ammunation Sales ($)",1},
		{"Deaths",1},
		{"Money Gained",1},
		{"Money Transferred",1},
		{"Hours Accumulated",1},
		{"Jail Time Served",1},
		{"Wanted Points Earned",1},
		{"Hits of Drugs Taken",1},
		{"# of Store Robberies",1},
		{"# of Failed Store Robberies",1},
		{"# of Successfull Store Robberies",1},
		{"# of Player Robberies",1},
		{"# of Failed Player Robberies",1},
		{"# of Successfull Player Robberies",1},
		{"$ lost due to Robberies",1},
		{"$ gained from Store Robberies",1},
		{"Attempted Bank Robberies",1},
		{"Successfull Bank Robberies",1},
		{"# of crimes committed",1},
		{"$ Taxed Overall",1},
		{"Attempted Armored Deliveries",1},
		{"Successfull Armored Deliveries",1},
	},
	{"Law",
		{"Arrests",1},
		{"Jails",1},
		{"Assists",1},
		{"Bribes Accepted",1},
		{"$ from Bribes",1},
		{"Deaths",1},
		{"Bullets Fired",1},
		{"# of Crime Reports",1},
		{"Attempted Patrol Missions",1},
		{"Successfull Patrol Missions",1},
		{"Total # of Patrol Calls",1},
	},
	{"Civilians",
		{"Deaths",1},
		{"Money Gained",1},
		{"Bus Driver Routes Completed",1},
		{"# of Fish Caught",1},
		{"$ of Fish Caught",1},
		{"# of Fires put out",1},
		{"# of Truck Deliveries",1},
		{"# of flights Completed",1},
	},
	{"Criminals",
		{"Deaths",1},
		{"Turfs Taken",1},
		{"Deaths in LV",1},
		{"Wanted Points evaded",1},
		{"Bullets Fired",1},
	}
}

local topDay = {
	{"Overall",
		{"Most Improved Score","who",1},
		{"Top Score [all time]","who",1},
		{"Worst Player of the Day","who",1},
	},
	{"Civilians",
		{"Best Bus Driver","who",1},
		{"Best Pilot","who",1},
		{"Best Trucker","who",1},
		{"Best Fisherman","who",1},
		{"Most Valuable Fish","who",1},
	},
	{"Law",
		{"Top Jailer","who",1},
		{"Best Assistant Cop","who",1},
		{"Most Arrests","who",1},
		{"Most Deaths","who",1},
		{"Most Corrupt","who",1},
		{"Worst Arrestor","who",1},
		{"Worst Jailer","who",1},
		{"Least Deaths","who",1},
		{"Biggest Responder","who",1},
	},
	{"Criminals",
		{"Taken the most turfs","who",1},
		{"Started the most attacks","who",1},
		{"Most Murders","who",1},
		{"Most Deaths","who",1},
		{"Top Store Robber","who",1},
		{"Worst Store Robber","who",1},
		{"Best Pick Pocket","who",1},
		{"Best Con Artist","who",1},
		{"Biggest Drugee","who",1},
	}
}

local topWeek = {
	{"Gangs",
		{"Taken LV The Most","swag",1},
		{"Taken the most turfs","swag",1},
		{"Died the most","The Smurfs",1},
	},
	{"Overall",
		{"Most Improved Score","who",1},
		{"Top Score [all time]","who",1},
		{"Worst Player of the Week","who",1},
	},
	{"Civilians",
		{"Best Bus Driver","who",1},
		{"Best Pilot","who",1},
		{"Best Trucker","who",1},
		{"Best Fisherman","who",1},
		{"Most Valuable Fish","who",1},
	},
	{"Law",
		{"Top Jailer","who",1},
		{"Best Assistant Cop","who",1},
		{"Most Arrests","who",1},
		{"Most Deaths","who",1},
		{"Most Corrupt","who",1},
		{"Worst Arrestor","who",1},
		{"Worst Jailer","who",1},
		{"Least Deaths","who",1},
		{"Biggest Responder","who",1},
	},
	{"Criminals",
		{"Taken the most turfs","who",1},
		{"Started the most attacks","who",1},
		{"Most Murders","who",1},
		{"Most Deaths","who",1},
		{"Top Store Robber","who",1},
		{"Worst Store Robber","who",1},
		{"Best Pick Pocket","who",1},
		{"Best Con Artist","who",1},
		{"Biggest Drugee","who",1},
	}
}

secs=100
for k,v in pairs(topWeek) do
	for k2,v2 in pairs(v) do
		if k2 ~= 1 then
		setTimer(function()
			local p = getRandomPlayer()
			local name = getPlayerName(p)
			for _,player in pairs(getElementsByType("player")) do
				exports.dendxmsg:createNewDxMessageBot(player," #33FF00 [Gameplay]["..v[1].."] "..v2[1].." #FFFF33"..name.." with [var]",255,255,0)
			end
		end,secs,1)
		if secs > 3000 then
			secs=secs+5000
		else
			secs=secs+1000
		end
		end
	end
end
