------------------------------------------------------------------------------------
--  For CSG Server
--  Verson 1.0.0
--  CSGstaffsteath/server (server-side)
--  Staff Preventing STEATH Script
--  [CSG]Smith
------------------------------------------------------------------------------------