addEventHandler("onClientResourceStart",resourceRoot,
function()
	local rX,rY = guiGetScreenSize() --get players resolution
	local width,height = 770,560
	local X = (rX/2) - (width/2)
	local Y = (rY/2) - (height/2)
	
	managerWindow = guiCreateWindow(X,Y,width,height,"CSG Store - Manger",false)
		guiSetAlpha(managetWindow,1)
		guiSetMovable(managerWindow,false)
		guiSetSizable(managerWindow,false)
	lbl = guiCreateLabel(371,19,15,537,"|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n|\n",false,mangerWindow)
		guiLabelSetVerticalAlign(lbl,"center")
		guiLabelSetHorizonalAlign(lbl,"center")
	transactionGrid = guiCreateGridList(9,102,362,449,false,managerWindow)
		guiGridListAddColumn(transactionGrid,"ID",0.2)
		guiGridListAddColumn(transactionGrid,"Name",0.2)
		guiGridListAddColumn(transactionGrid,"TID",0.2)
		guiGridListAddColumn(transactionGrid,"ITEM",0.2)
		guiGridListAddColumn(transactionGrid,"Manager",0.2
		guiGridListSetSelectionMode(transactionGrid,2)
		
	buttons["getTransactions"] = guiCreateButton(9,23,132,32,"Get Transactions",false,managerWindow)
	buttons["clearTransactions"] = guiCreateButton(234,23,132,32,"Remove Transactions",false,managerWindow)
	buttons["updateTransaction"] = guiCreateButton(9,60,132,32,"Update Transaction",false,managerWindow)
	buttons["deleteTransaction"] = guiCreateButton(234,60,132,32,"DeleteTransaction",false,managerWindow)
	
	labels[1] = guiCreateLabel(397,487,92,25,"State",false,managerWindow)
	labels[2] = guiCreateLabel(395,112,357,25,"Transaction ID",false,managerWindow)
	labels[3] = guiCreateLabel(395,170,357,25,"Email",false,managerWindow)
	labels[4] = guiCreateLabel(395,230,357,25,"Status",false,managerWIndow)
	labels[5] = guiCreateLabel(395,292,357,25,"Issuer",false,managerWIndow)
	labels[6] = guiCreateLabel(395,354,357,25,"Date",false,managerWindow)
	labels["trDL"] = guiCreateLabel(399,30,359,57,"Username: N/A, Item ID: N/A",false,managerWindow)
	
	edits["transaction"] = guiCreateEdit(394,136,358,25,"",false,managerWindow)
	edits["email"] = guiCreateEdit(394,194,358,25,"",false,managerWindow)
	edits["status"] = guiCreateEdit(394,254,358,25,"",false,managerWIndow)
	edits["state"] = guiCreateEdit(407,452,71,25,"",false,managerWindow)
	edits["issuer"] = guiCreateEdit(394,318,358,25,"",false,managerWindow)
	edits["date"] = guiCreateEdit(394,378,358,25,"",false,managerWIndow)
	
	
GUIEditor_Label[2] = guiCreateLabel(397,487,92,25,"State",false,GUIEditor_Window[1])
guiLabelSetVerticalAlign(GUIEditor_Label[2],"center")
guiLabelSetHorizontalAlign(GUIEditor_Label[2],"center",false)
GUIEditor_Label[3] = guiCreateLabel(395,112,357,25,"Transaction ID",false,GUIEditor_Window[1])
guiLabelSetVerticalAlign(GUIEditor_Label[3],"center")
guiLabelSetHorizontalAlign(GUIEditor_Label[3],"center",false)
GUIEditor_Edit[1] = guiCreateEdit(394,136,358,25,"transaction ID",false,GUIEditor_Window[1])
GUIEditor_Label[4] = guiCreateLabel(395,170,357,25,"Email",false,GUIEditor_Window[1])
guiLabelSetVerticalAlign(GUIEditor_Label[4],"center")
guiLabelSetHorizontalAlign(GUIEditor_Label[4],"center",false)
GUIEditor_Edit[2] = guiCreateEdit(394,194,358,25,"email",false,GUIEditor_Window[1])
GUIEditor_Label[5] = guiCreateLabel(395,230,357,25,"Status",false,GUIEditor_Window[1])
guiLabelSetVerticalAlign(GUIEditor_Label[5],"center")
guiLabelSetHorizontalAlign(GUIEditor_Label[5],"center",false)
GUIEditor_Edit[3] = guiCreateEdit(394,254,358,25,"status",false,GUIEditor_Window[1])
GUIEditor_Edit[4] = guiCreateEdit(407,452,71,25,"state",false,GUIEditor_Window[1])
GUIEditor_Label[6] = guiCreateLabel(395,292,357,25,"Issuer",false,GUIEditor_Window[1])
guiLabelSetVerticalAlign(GUIEditor_Label[6],"center")
guiLabelSetHorizontalAlign(GUIEditor_Label[6],"center",false)
GUIEditor_Edit[5] = guiCreateEdit(394,318,358,25,"Issuer",false,GUIEditor_Window[1])
GUIEditor_Label[7] = guiCreateLabel(395,354,357,25,"Date",false,GUIEditor_Window[1])
guiLabelSetVerticalAlign(GUIEditor_Label[7],"center")
guiLabelSetHorizontalAlign(GUIEditor_Label[7],"center",false)
GUIEditor_Edit[6] = guiCreateEdit(394,378,358,25,"date",false,GUIEditor_Window[1])
buttons["update"] = guiCreateButton(498,450,117,33,"Update",false,GUIEditor_Window[1])
guiSetFont(buttons["update"],"default-bold-small")
buttons["close"] = guiCreateButton(628,450,117,33,"Close",false,GUIEditor_Window[1])
guiSetFont(buttons["close"],"default-bold-small")
transactionDataLbl = guiCreateLabel(399,30,359,57,"Username: \"..username..\", Item ID: \"..itemID..\"",false,GUIEditor_Window[1])
guiLabelSetColor(transactionDataLbl,0,255,0)
guiLabelSetVerticalAlign(transactionDataLbl,"center")
guiLabelSetHorizontalAlign(transactionDataLbl,"center",false)
guiSetFont(transactionDataLbl,"default-bold-small")


guiSetFont(buttons["deleteTransaction"],"default-bold-small")