theLatestVersion = 311
version = "2.2.0"
theMainData = {
        {311,"2.3","December 12th 2013",
            {
                {"> test.","(CSG)Soap.-"},
            }
        },
        {311,"2.2.0","July 11th 2013",
            {
                {"> [Feature] Added lagg checker. /checklagg for details.","[CSG]Jack"},
                {"> [Bug-Fix] Fixed lagg at LS Fishing Area","[CSG]Jack"},
                {"> [Bug-Fix] Alliance system fixed. All new alliance will be bugless","[CSG]Priyen"},
                {"               All old alliances -> REMAKE THEM ASAP",""},
            }
        },
        {310,"V2.1.9","July 9th 2013",
            {
                {"> [Bug-Fix] Fixed reload exploit by jumping while reloading.","[CSG]Jack"},
            }
        },
        {309,"V2.1.8","July 9th 2013",
            {
                {"> [Bug-Fix] FPS not being sent properly serverside.","[CSG]Jack"},
                {"> [Temp-Bug-Fix] Added a small code to help turfing not bug as much",""},
                {"> [Feature] Added 'ID' column on /punishments",""},
                {"    Use ID when appealing punishments!",""},
                {"> [Tweak] Math Quiz made harder.","[CSG]Smith"},
                {"   Winnings: $800 - 1,200 & 0.5 score",""},
                {"   Loosing: $100 & -0.5 score",""},
            }
        },
        {308,"V2.1.7","July 8th 2013",
            {
                {"> [Bug-Fix] Shooting team mates while on bikes caused killing FIXED!","[CSG]Jack"},
                {"> [Bug-Fix] PING indicator not being properly calculated",""},
                {"> [Bug-Fix] Server core resource causing major spam fixed.", ""},
                {"> [Bug-Fix] Fixed AT exploit",""},
            }
        },
        {307,"V2.1.6","July 3rd 2013",
            {
                {"> [Bug-Fix] Tag protection fixed, before it would randomly rename your name.","[CSG]Priyen"},
                {"> [Bug-Fix] Youtube links fixed again",""},
                {"            non-vevo and new links ONLY",""},
                {"> [Bug-Fix] Losing armor on job change fixed",""},
            }
        },
        {306,"V2.1.5","July 3rd 2013",
            {
                {"> [Feature] Added weather system (type /weather [id])","[CSG]Jack"},
                {"> [Bug-Fix] Fixed PING bars not working again","[CSG]Jack"},
            }
        },
        {305,"V2.1.5","July 2nd 2013",
            {
                {"> [Feature] Added Anti-Lagg script.","[CSG]Jack"},
                {"     10 FPS or lower will disable weapon firing",""},
                {"     400 Ping or higher disable weapon firing",""},
                {"> [Disable] Disabled 'tag remover' as its bugged.",""},
                {"> [Bug-Fix] Some weird bug storing players FPS serverside",""},
                {"> [Re-code] Recoded clientside FPS and serverside storage",""},
                {"",""},
                {"> [Bug-Fix] PING bars not working properly","nero[sm]"},
            }
        },
        {304,"V2.1.4","July 2nd 2013",
            {
                {"> [UPDATE] Server updated to V1.3.3","[CSG]Jack"},
            }
        },
        {303,"V2.1.3->2.1.4","July 2nd 2013",
            {
                --{"END SHIFT or QUIT JOB if you don't get assigned a team in TAB",""},
                {"> [Major-Fix] Fixed MySQL to stop dropping from MySQL","[CSG]Jack"},
                {"> [Feature] Players below 800x600 are no longer kicked. Instead, given instructions.",""},
                {"> [Feature] Added Account Scanner. Prevents double account fully.",""},
                {"> [Feature] Added FPS and PING Indicator (Thanks nero!)",""},
                {"> [Feature] Added getPlayerFPS() for developers.",""},
                {"> [Feature] Added getPlayerGroup() and getPlayerGroupRank()",""},
                {"> [Bug-Fix] Fixed FPS and PING indicators, they now show constantly.",""},
                {"",""},

                {"> [Feature] [CSG] tag is now protected, prevents imposters","[CSG]Priyen"},
                {"> [Bug-Fix] Damage proof bug via mech job fixed",""},
                {"> [Bug-Fix] Tazer abuse bug via /stopanim and sprint fixed",""},

            }
        },
        {300,"v.2.1.2","June 28th, 2013",
            {
                {"> [Bug-Fix] Youtube in Phone now fixed","[CSG]Priyen"},
                {"          Only new links and non-vevo links will work",""},

            }
        },
        {299,"v.2.1.1","June 19th, 2013",
            {
                {"> [Bug-Fix] HP Exploit in food shops fixed","[CSG]Priyen"},
                {"> [Bug-Fix] Police Chief for SWAT Team fixed",""},
                {"> [Bug-Fix] Assassin skill ghost exploit fixed",""},
                {"> [Bug-Fix] Armor Exploit in ammunations fixed",""},
                {"> [Bug-Fix] Instant plant mine fixed",""},
                {"> [Bug-Fix] Instant change wheel fixed",""},
                {"> [Bug-Fix] Instant use fuel can fixed",""},
                {"> [Bug-Fix] /sellweps + it's exploit fixed",""},
                {"> [Bug-Fix] /crimes fixed",""},
            }
        },
        {296,"v.2.1.0","June 6th, 2013",
            {
                {"> [Feature] Skateboard added around SA","Prime"},
                {"> [Feature] You can now buy 10 medkits, (previously only 5)","Prime"},
                {"> [Feature] Anti-nade spam added","Prime"},

            }
        },
        {295,"v.2.0.8","May 29th, 2013",
            {
              {"> [Feature] CountryRifle clips changed to 2, damage changed -50%","Prime"},
              {"            Smoke system /cs can be used for Cops/Crims",""},
              {"            payments changed to 2k per 1 Smoke",""},
              {"> [Bug-Fix] You can no longer rob negative money","[CSG]Priyen"},
            }
        },
        {294,"v.2.0.7","May 21st, 2013",
            {
                {"> [Feature] Compact list of CSG's commands -> type /cmds","Prime"},
                {"> [Feature] Players will have helmets when they are on bikes","Prime"},
                {"> [Bug-Fix] Share Gates in alliance GUI fixed","[CSG]Priyen"},
                {"> [Bug-Fix] Removed fbi skin from clothes shop","[CSG]Priyen"},


            }
        },
        {292,"v.2.0.6","May 17th, 2013",
            {
                {"> [Feature] Fuel canisters are now on sale, buy from fuel stations","Prime"},
                {"            Use them by typing /gsc near a vehicle!",""},
                {"            (To refuel a vehicle)",""},
                {"> [Feature] Spare tires are now on sale, buy from mechanic job locations","Prime"},
                {"            Use them by typing /tire near a vehicle!",""},
                {"            (To repair the wheels on a vehicle)",""},
                {"> [Bug-Fix] Alliance system fixed","[CSG]Priyen"},
                {"> [Bug-Fix] Car fixing fixed - you can only repair it now 90% hp+","[CSG]Priyen"},
                --{"> [Bug-Fix] You were able to turf with some heli's fixed","[CSG]Priyen"},
            }
        },
        {290,"v.2.0.5","May 14th, 2013",
            {
                {"> [Bug-Fix] You could drive broken cars fixed","[CSG]Priyen"},
                {"> [Bug-Fix] You could drive official law vehicles fixed","[CSG]Priyen"},
                {"> [Bug-Fix] You could spam buy medkits fixed","[CSG]Priyen"},
                --{"> [Bug-Fix] You were able to turf with some heli's fixed","[CSG]Priyen"},
            }
        },
        {289,"v.2.0.4","May 10th, 2013",
            {
                {"> [Feature] New Party / Night club hall near Limo job","Prime"},
                {"            Relax and have some fun and a great time with nice music!"},
                {"> [Bug-Fix] New Download system adjusted to fix lag (skins should work now)","[CSG]Priyen"},
                {"> [Bug-Fix] Throwing nade while being tazered fixed",""},
                {"> [Bug-Fix] 'punching' while being tazered fixed",""},
                {"> [Bug-Fix] When a cop ended job, or died while he arrested someone",""},
                {"            you wouldn't get released, fixed now"},
                {"> [Bug-Fix] Limo Driver job dx label fixed",""},
                {"> [Bug-Fix] Mansion Raid now ends at 5 peds remaining. Though more spawn now.",""},
                {"            Added this because peds often get bugged and 1-5 are missing sometimes"},
            }
        },
        {288,"v.2.0.3","May 7th, 2013",
            {
                {"> [Bug-Fix] Car Fix causing lag bug fixed","[CSG]Priyen"},
                {"> [Bug-Fix] Ammo exploit in /hp fixed","[CSG]Priyen"},
                {"> [Bug-Fix] You were able to turf with some heli's fixed","[CSG]Priyen"},
            }
        },
        {286,"v.2.0.2","May 6th, 2013",
            {
                {"> [Feature] All non-essential files will now be downloaded in the background",""},
                {"            Basically now in CSG you can connect without downloading mods",""},
                {"            The system will transfer the mods to you if you stay connected",""},
                {"            long enough. (You won't see the 'download progress')...",""},
                {"            Essentially once all mods in CSG have been transferred,",""},
                {"            Download size for new players will be much much less",""},
                {"> [Feature] Most skin mods moved to new download system",""},
                {"> [Feature] New Lamborghini added in Vehicle Shops",""},
                {"            (Using new download system) Mod suggested by Benja",""},
            }
        },
        {284,"v.2.0.1","May 4th, 2013",
            {
                {"> [Bug-Fix] Alliance group invite bug fixed","[CSG]Priyen"},
                {"> [Bug-Fix] Paramedic stat saving fixed","[CSG]Priyen"},
            }
        },
        {283,"v.2.0.0","May 2nd, 2013",
            {
                {"> [Feature] New modshop by Dennis added",""},
                {"> [Bug-Fix] Drug - House bug fixed","[CSG]Priyen"},
                {"> [Bug-Fix] Vehicle damage proof paynspray bug fixed","[CSG]Priyen"},
                {"> [Feature] 1 of 2 events scheudled for this week added","[CSG]Priyen"},
                {"            Mansion Raid -> go to raid icon on map",""},
                {"            Type /raidtime for details!",""},
                {"> [Feature] LV Food Stores - Criminals can now enter once only per 5 minutes","[CSG]Priyen"},
                {"            Stores would be abused during wars..turfing..etc",""},
                {"> [Bug-Fix] Abusable house selling bug fixed","[CSG]Priyen"},
                {"> [Bug-Fix] /sellweps can't set ammo price fixed","[CSG]Priyen"},
                {"> [Bug-Fix] Cargobob magnet /magup and /magdown fixed","[CSG]Priyen"},
                {"> [Feature] Train Travel system added in each city","Prime"},
                {"            Updated so you can go in both directions now (previous or next city)",""},
                {"            Now you can only ride train if you have 0 wanted points",""},
                {"> [Feature] LV Food Stores - Criminals can now enter once only per 5 minutes","[CSG]Priyen"},
                {"            Stores would be abused during wars..turfing..etc",""},
                {"> [Bug-Fix] Armor Shop GUI outside of stores fixed","[CSG]Priyen"},
                {"> [Bug-Fix] Drive-Thru fixed","[CSG]Priyen"},
                {"> [Feature] Train Travel system added in each city","Prime"},
                {"            For $1000 you can ride to the next city{ (LS->SF->LV-LS)",""},
                {"            Use /stoptrain to stop a train mid-way if you wish",""},
                {"> [Bug-Fix] Phone Setting should now save (tested multiple times)","[CSG]Priyen"},

                {"> [Feature] Turfing Bar no longer shows while F11 is open","[CSG]Priyen"},
                {"> [Feature] /crimes now shows your wanted level / points","[CSG]Priyen"},
                {"> [Feature] Drug Shipment -> Boosted","[CSG]Priyen"},
                {"            50 Drug Points per Crate and 50 For participating in DS ",""},
                {"            Applies for both Law and Criminals",""},
                {"            More Drug Points per Kill ",""},
                {"> [Feature] New Radio Tower -> LV Sea","[CSG]Priyen"},
                {"            Turf map updates by Ryder and Hamza ",""},
                {"            New Turf in North East LS (SEA) ",""},
                {"            Sea Turfs now give more money and score (not much)",""},
                {"            Free boat spawner @ boat shop and the most north turf",""},
                {"> [Feature] New Housing @ one of the turfs! Buy them while they last!","[CSG]Priyen"},
                {"> [Feature] Handbrake - Press Left Shift to toggle it in vehicle","Prime"},

                {"> [Feature] New LV/LS Toll Gates, no bugs + RP $50 to cross","Prime"},
                --{"> [Feature] Handbrake - Press Space to toggle it in vehicle","Prime"},
                {"> [Feature] Lumberjack ranks added + bonus salary",""},
                {"            Ranks by Benja",""},
                {"> [Bug-Fix] Drug Points from DS now save on reconnect [during the DS time]","[CSG]Priyen"},
                {"> [Bug-Fix] Taking 0.001 of a drug, fixed","[CSG]Priyen"},
                {"> [Bug-Fix] You can use jetpack while wanted, fixed","[CSG]Priyen"},
                {"> [Bug-Fix] You can no longer use food store GUI outside (abusable fixed)","[CSG]Priyen"},

                {"> [Bug-Fix] Lumberjack Spawners fixed","[CSG]Priyen"},
                {"> [Bug-Fix] Med Pack negativity issues fixed","[CSG]Priyen and Prime"},
                {"> [Bug-Fix] CJ Muscles now save upon reconnect","[CSG]Priyen"},
                {"> [Bug-Fix] House System enter 'Press H'..etc","[CSG]Priyen"},
                {"> [Bug-Fix] Alliance system creation fixed","[CSG]Priyen"},
                {"> [Feature] Airport Attendant job added @ LS Airport","Prime"},
                {"> [Feature] /armortime command to see Armored Transport event status","[CSG]Priyen"},
                {"> [Feature] New Dice event (run by admins) mapped by Gusolina and Pranav",""},
                {"> [Feature] Heroine system changed","[CSG]Priyen"},
                {"            'Old' Heroine added back",""},
                {"            Heroine won't work if your ping is higher then 400",""},
                {"            Heroine also wont work when you have armor",""},
                {"> [Feature] Lumberjack job added right of SF","[CSG]Priyen"},
                {"            Attractive pay $$$ + stable income",""},
                {"            Thank You: Barbosa, Benja, Gusolina, Ero for mapping tree's",""},
                {"> [Feature] Added Rescuer job!","[CSG]SpriN"},
                {"            the spawners for other jobs also fixed",""},
                {"> [Feature] Added New Flag Event - no bugs!","[CSG]SpriN"},
                {"> [Bug-Fix] Mail Officer job bug fixed","Prime"},
                {"> [Feature] Fuel Tank Driver job added @ LS docks area","Prime"},
                {"> [Bug-Fix] Mail Officer job bug fixed","Prime"},
                {"> [Feature] Wanted players can now surrender for less jail time","[CSG]Priyen"},
                {"            Type /surr to give up and surrender if wanted",""},
                {"            NOTE: You will not get reduced time if you /surr without",""},
                {"            being warned, this is to prevent abuse and trolling.",""},
                {"            You must comply within 10 seconds for less time",""},
                {"> [Feature] Law can now warn players to pull over or surrender","[CSG]Priyen"},
                {"            Use /warn to warn the nearest player if wanted",""},
                {"            The jailer will get 25% more for arresting a warned criminal",""},
                {"            Though the criminal must comply within 10 seconds",""},

                {"> [Feature] iPhone Icons Pack (amazing) made by Ryder added!",""},
                {"> [Feature] Sea Turfs added","[CSG]Priyen"},
                {"            csgmta.net --> VOTE REGARDING SEA TURFS",""},
                {"            RT's for sea turfs will be added when decided on location",""},
                {"> [Bug-Fix] Criminals got wanted for spawning vehicles - fixed","[CSG]Priyen"},
                {"> [Bug-Fix] /lock fixed","[CSG]Priyen"},
                {"> [Feature] Delievery Man job added at North East LS","Prime"},
                {"> [Feature] You can now buy medic packs @ Hospital's for money","Prime"},
                {"            Type /medkit to use if you have one",""},
                {"> [Feature] Female Police Officer added (skin 283)","Prime"},
                {"> [Feature] New Weapon Clips added","Prime"},
                {"            Some weapons will have 30,40, or 50 ammo based on the",""},
                {"            weapon skill level you have for it",""},
                {"> [Feature] CJ Muscle Skills / Stats added @ LS GYM","Prime"},
                {"            Increase your strength, muscles! [CJ ONLY]!",""},
                {"> [Feature] Mail Officer job added near LSPD","Prime"},
                {"            Earn money by deleivering Mail to homes!",""},
                {"> [Feature] Pizza Boy job added @ LS Pizza Restaurant","Prime"},
                {"            Earn money by deleivering Pizza's!",""},
                {"> [Bug-Fix] Phone Music / Youtube FIXED",""},
                {"            OLD songs wont work, but NEW will!",""},
                {"> [Bug-Fix] Drug Detective blip and spawner missing bug fixed",""},
                {"> [Bug-Fix] SMS + Vehicle HUD bug fixed",""},
                {"> [Feature] Flashbang functionality added","Prime"},
                {"            Ammunations now sell 'Special' Tear gas",""},
                {"            Get some tear gas and use /bang to toggle",""},
                {"> [Feature] Taxi Driver Job Added @ LS","Prime"},
                {"            Earn money and transport passengers!",""},
                {"> [Feature] News Reporter Job Added @ LS","[CSG]Priyen"},
                {"            Take pictures of wanted players and move up the ranks!",""},
                {"            Job has 7 ranks w/ bonus salary",""},
                {"            GUI by Sathler",""},
                {"> [Feature] A Limo Driver job Added!","[CSG]SpriN"},
                {"> [Feature] Drug Detective job added @ LSPD Basement!","Prime"},
                {"> [Feature] Added a side-mission to Paramedic's to respond to civilians in need","Prime"},
                {"            Marker at All Saints in LS",""},
                {"> [Feature] Daily Salary for Paramedic added ( every game day you get paid a bonus )","[CSG]Priyen"},
                {"            More Jobs coming soon to the daily salary system",""},
                {"> [Feature] Paramedic stats + ranks added in F5 panel.","[CSG]Priyen"},
                {"> [Feature] Added a new mini-event - find the armor and deliever it for rewards","Prime"},
                {"            This will automatically alternate between the flag and the armor.",""},
                {"            Once it will be flag, next time armor, repeat, etc",""},
                {"> [Bug-Fix] Law and Criminal mine bugs fixed (infinite exploding+marker bug)!",""},
                {"> [Feature] Use your engine to the limits now for only $4000 via /cs [criminals]",""},
                {"> [Feature] Fisherman salary increased 30%!",""},
                {"> [Feature] DX Head Labels are places of interest, jobs, etc!","[CSG]SpriN"},
                {"> [Bug-Fix] Sawn-off 4 ammo shot fixed, only 2 bullets will damage now",""},
                {"> [Feature] Added more law vehicles to High speed unit rank!",""},
                {"> [Feature] Alliance system -> Blips + 'Turf as Alliance' fixed!",""},
                {"> [Feature] Bomb Shop Added, pay $3000 to have your veh rigged!","Prime"},
                {"            Go to 'C' blips on map, bomb w/ detenator",""},
                {"> [Feature] Car Wash! You can now wash your car at select places","Prime"},
                {"            Over time your vehicle could get dirty, so wash it!",""},
                {"> [Feature] Updated flash light - use /flash","Prime"},
                {"> [Feature] /smoke and /drink added, use it when you feel like getting high!","Prime"},
                {"> [Feature] New Animation Commands:","Prime"},
                {"            Law: /costop /comove /comove /cogo /cocome",""},
                {"            All Others: /hand",""},
                {"> [Feature] Now theres a Mystery Bag! Find it for a satisfying reward","Prime"},
                {"> [Feature] Law Mines Added -> USE with Explosives Unit for $2500","Prime"},
                {"            Use /lmine to place, /delmine to remove!",""},
                {"> [Feature] Criminal Mines Added -> USE with Bomb Expert for $5000","Prime"},
                {"            Use /cmine to place, /delmine to remove!",""},
                {"> [Bug-Fix] Settings now actually save, in phone!","[CSG]Fabio"},
                {"> --------------------------------------------------------------------------------- ",""},
                {"> [Feature] RPG system - you can buy a RPG in LV with /buyrpg. Each rocket ","[CSG]Frost"},
                {"           will cost 9k. You can hold 3 at the same time and you can only",""},
                {"           buy 3 every 15 minutes.",""},
                {"> [Feature] You can now fix you car (owned and spawned) if it has more than 90% health ","[CSG]Frost"},
                {"           Get close to your car and press right mouse button.",""},
                {"> [Feature] You can now change your car's drive type, which means you can set it front","[CSG]Frost"},
                {"           rear or all wheel drive. When inside a car use the command",""},
                {"           /dtype rwd,fwd or awd. /dtype current will give you the current drive",""},
                {"            type and /dtype reset will reset it to default",""},
                {"> [Bug-Fix] This is a minor fix for the C-bug. Need more feedback about it.","[CSG]Frost"},
                {"           If it doesn't work, please send me a forum PM.",""},
                {"> [Bug-fix] Weapon Drop was rewriten and should not create bugged weapon pickups.","[CSG]Frost"},
                {"> [Feature] Cargobob Magnet - /magnet to create the magnet, move it up and","[CSG]Frost"},
                {"           down with num_+ and num_- or /magup and /magdown. To grab/release",""},
                {"           a vehicle use left control.",""},
                {"> [Feature] Law Skill -> High Speed unit - works with normal cars [eg. police LS]","[CSG]Priyen"},
                {"> [Feature] Alliance system w/ alliance chat-> type /ac or J","Priyen and Fabio"},
                {"            Likely bugs so please report them on the forum so I can fix them asap",""},
                {"> [Feature] Buyable Police cars, buy them from PD basements/garages.","[CSG]Priyen"},
                {"            You will get wanted for driving a cop car without being a cop!",""},


            }


        },
        {240,"v.1.9.5","April 4th, 2013",
            {
                {"> [Feature] Police Chief roster updated","[CSG]Priyen"},
                {"> [Feature] Law can now transfer a criminal in custody",""},
                {"            Type /arrtransfer or /arrt crimName copName to do so",""},
                {"            The 'arrested' point will count for the new officer only",""},
                {"> [Bug-Fix] Pilot rank's fixed - but you'll have to re-do the job"," "},
                {"            to get them back"," "},
                {"> [Feature] Anti-Ping added, you'll get notice if your ping is too high ","[CSG]Jack"},

            }
        },
        {239,"v.1.9.0","March 31st, 2013",
            {
                {"> [Feature] In-game Billboard @ LV Hospital Activated","[CSG]Priyen"},
                {"          Apply for ads in the forum @ Mappers Board!",""},
                {"          Billboards @ LS Hospital and other locations will be",""},
                {"          added within 24 hours (more spots being chosen)",""},
                {"> [Feature] Police Chief Added","[CSG]Priyen"},
                {"         Type /pchief to access related information",""},
                {"         Use /stats -> LAW to check who's a chief",""},
                {"         Some police chief's have already been selected",""},
                {"          based on their law performance.",""},
                {"         You will be contacted if you are that person, have fun!",""},
            }
        },
        {238,"v.1.7.2","March 21st, 2013",
            {
                {"> [Feature] Flash Light Added! Use /flash to toggle!","Prime"},
                {"           It will only work with weapons! So use it after",""},
                {"           you put on a weapon",""},
                {"> [Feature] GTA wall bug fix in LV by mhmd","[CSG]Priyen"},
                {"> [Feature] Added command /cleardx to clear dx messages on screen","[CSG]Priyen"},
                {"> [Feature] House Selling Price (Max) changed to infinity",""},
                {"> [Bug-Fix] Phone music not saving fixed"," "},
                {"> [Bug-Fix] Support unit's dropping spray can fixed"," "},
            }
        },
        {235,"v.1.7.1","March 19th, 2013",
            {
                {"> [Bug-Fix] Critical abusable bug in /selldrugs fixed","[CSG]Jack"},
                {"> [Change] Drug - Heroine no longer works when having armor","[CSG]Priyen"},
                {"           Additionally, a bug was fixed that when you were",""},
                {"           damaged too fast, you would regen hp instead (fixed now)",""},

            }
        },
        {233,"v.1.7.0","March 18th, 2013",
            {
                {"> [Feature] Walking Styles have been added!","Prime and Priyen"},
                {"            Time to add some flavour into your style of walking",""},
                {"            Change your walking style at the LS or LV gym's",""},
                {"            It costs $500 to change, enjoy and have fun!",""},

            }
        },
        {232,"v.1.6.9","March 15th, 2013",
            {
                {"> [Feature] /eventnote added for events!","[CSG]Assassino"},
                {"> [Feature] CSG Phone Youtube system back up!","[CSG]Priyen"},
                {"            If old links do not work, re-add them!",""},
                {"            Most of them will work without issues.",""},
                {"> [Feature] Added some logging to Event system","[CSG]Priyen"},
            }
        },
        {231,"v.1.6.8","March 13th, 2013",
            {
                {"> [Bug-Fix] Some LV Fake walls map fixes by mhmd",""},
                {"> [Bug-Fix] Bike / Cycle skills - passengers no longer get exp","[CSG]Priyen"},
                {"> [Feature] Egyptian chat added to 'J', requested by [CSG]Maxil",""},
                {"> [Bug-Fix] Bike / Cycle skills fixed","[CSG]Priyen"},
                {"            For some players it might have reset",""},
                {"            But now you won't lose them",""},
                {"> [Bug-Fix] /engine 0 Fuel Bug fixed",""},
                {"> [Bug-Fix] PayNSpray damage proof bug fixed",""},
                {"> [Bug-Fix] You can knife a arrested person fixed",""},
                {"> [Bug-Fix] Losing weapons when disconnecting while dead FIXED!",""},
                {"> [Bug-Fix] Law Skills lost on reconnect fixed",""},
                {"> [Bug-Fix] Criminal Skills lost on reconnect fixed",""},
                {"> [Bug-Fix] Fixed a bug where the 'you last logged into CSG' was innaccurate",""},
                {"> [Change] stealth kill limited to once per 5 minutes",""},
            }
        },
        {226,"v.1.6.7","March 12th, 2013",
            {
                {"> [Feature] CSG Stats system added","[CSG]Priyen"},
                {"            A lot of cool stats you can check out!",""},
                {"            Rankings too for those stats! (These update hourly)",""},
                {"            Stats that show 'unavailable' are not enabled, but most are!",""},
                {"            Use /stats to access",""},
                {"> [Bug-Fix] Group system making a group fixed",""},
                {"> [Bug-Fix] Damage proof bug fixed (vehicles)",""},
                {"> [Bug-Fix] Clothes shop CJ skin bug fixed",""},
                {"> [Bug-Fix] Now you cant use /pc in a interior",""},
                {"> [Bug-Fix] Now you can't drop eg. 0.5 ammo",""},
                {"> [Bug-Fix] Vehicle shops don't warp you to your new vehicle fixed",""},
                {"> [Bug-Fix] Viewing Stats of people who aren't logged in fixed",""},
                {"> [Bug-Fix] Despawn respawn vehicles position fixed",""}, -- need to do

            }
        },
        {224,"v.1.6.5","March 9th, 2013",
            {
                {"> [Feature] Mystery Van --> drugs, weapons","[CSG]Smith"},
                {"> [Bug-Fix] Lag due to CSGturfing fixed",""},
            }
        },
        {223,"v.1.6.4","March 9th, 2013",
            {
                {"> [Bug-Fix] Knife / stealth kill fixed for butcher skill","[CSG]Priyen"},
                {"> [Feature] Philippines Chat Room added in J",""},
                {"> [Bug-Fix] Gates with slanted surfaces are now fixed (open/close)","[CSG]Priyen"},
                {"            (Again, but now works 100%)",""},


            }
        },
        {221,"v.1.6.3","March 6th, 2013",
            {
                    {"> [Bug-Fix] Gates with slanted surfaces are now fixed (open/close)","[CSG]Priyen"},



            }
        },
        {219,"v.1.6.2","March 4th, 2013",
            {
                {"> [Feature] Heli blade killed removed, replaced by: ","Prime & Assassino"},
                {"            Blades doing progressive damage",""},


            }
        },
        {218,"v.1.6.1","February 28th, 2013",
            {
                {"> [Feature] Players who DC to be 'jailed faster' are now fined 5 Score",""},
                {"            This only applies for players who /quit, or /reconnect.",""},
                {"> [Bug-Fix] Fixed a bug where some CSGhousing houses weren't on sale","[CSG]Priyen"},
                {"> [Bug-Fix] Arrested players who DC give same rewards as jailing",""},
                {"> [Bug-Fix] Jailed players who DC give same rewards for arresting now",""},
                {"> [Bug-Fix] Bribe fixed",""},
            }
        },
        {217,"v.1.6.0","February 26th, 2013",
            {
                {"> [Bug-Fix] Bank rob paramedic bug fixed","[CSG]Priyen"},
                {"> [Bug-Fix] setfbijob fixed",""},
                {"> [Bug-Fix] Premium hats now work in interiors",""},
                {"> [Change] Explosives unit changed so it only works on wanted players",""},
                {"           Also doesn't work in Radio Turfs",""},
            }
        },
        {215,"v.1.5.9","February 23rd, 2013",
            {
                {"> [Feature] CSG's Sub-domains are now fixed","[CSG]Sensei"},
                {"      irc.csgmta.net, mta.csgmta.net",""},
                {"> [Bug-Fix] House Weapons bug fixed","[CSG]Priyen"},
                {"> [Bug-Fix] You can now only bribe the cop that arrested you",""},
                {"            Was meant to be like that initially",""},
                {"> [Bug-Fix] Abusable weapons selling fixed",""},
                {"> [Bug-Fix] Abusable mod shop shutdown bug fixed",""},
                {"> [Bug-Fix] House Drugs bug fixed",""},
                {"> [Bug-Fix] Abusable donut food menu bug fixed",""},
            }
        },
        {212,"v.1.5.9","February 18th, 2013",
            {
                {"> [Feature] Added M as a bind for lights","Prime"},
                {"> [Bug-Fix] House storage drug bug, fixed","[CSG]Jack"},
                {"> [Bug-Fix] Phone's remove music button fixed","[CSG]Priyen"},
                {"> [Bug-Fix] Vehicle spawners -> colors fixed",""},
                {"> [Bug-Fix] Abusable wanted points bug in houses fixed",""},
                {"> [Bug-Fix] You can drop weps in a house, abuse a bug in /hp",""},
                {"> [Bug-Fix] House permissions messed up, fixed",""},
                {"> [Bug-Fix] Spawn protected -> can't use weapons, fixed",""},
                {"> [Bug-Fix] Turf respawn > Hospital or Turf fixed",""},
                {"> [Change] Turf respawn doesn't spawn you in turf of death",""},
                {"> [Bug-Fix] Ferrari model restored",""},
            }
        },
        {210,"v.1.5.8","February 16th, 2013",
            {
                {"> [Feature] /lights to toggle lights, /od and /cd to close vehicle doors","Frost"},
                {"      /od DOOR# (1-6) /cd DOOR# (1-6)",""},
                {"> [Bug-Fix] Bike skills fixed","[CSG]Priyen"},
                {"> [Bug-Fix] Medic can now heal people even when using ecstasy","[CSG]Priyen"},
                {"> [Bug-Fix] You can't accept a bribe from someone who is jailed","[CSG]Priyen"},
            }
        },
        {209,"v.1.5.7","February 15th, 2013",
            {
                {"> [Bug-Fix] Bug-Fix, knife doesn't work on spawn protected people",""},
                {"> [Change] Butcher can now stealth kill",""},
                {"> [Change] Butcher score requirement -> 800",""},
                {"> [Change] Assassin can no longer stealth kill",""},
                {"> [Change] Assassin's effect only works on headshots",""},
                {"> [Change] Assassin score requirement -> 1500",""},
                {"> [Bug-Fix] Abusable drugs in houses fixed","[CSG]Jack"},
                {"> [Bug-Fix] Refueling is Free fixed","[CSG]Priyen"},
                {"> [Bug-Fix] Dropping full weapon ammo fixed","[CSG]Priyen"},
                {"> [Bug-Fix] Sell other player's house fixed","[CSG]Priyen"},

            }
        },
        {207,"v.1.5.6","February 13th, 2013",
            {
                {"> [Bug-Fix] Abusable infinite wanted level fixed","[CSG]Priyen"},
                {"> [Bug-Fix] You can't rob yourself now","[CSG]Priyen"},
                {"> [Notif.] Monster Build status 44%","Dev. Team"},
                {"> [Bug-Fix] Forum's online players count page fixed","[CSG]Jack"},
                {"> [Bug-Fix] Chat Spam via group deposit fixed","[CSG]Jack"},
                {"> [Bug-Fix] A bug-fix to Bike skills, but needs to be tested more","[CSG]Jack"},
            }
        },
        {204,"v.1.5.4","February 11th, 2013",
            {
                {"> [Feature] Phone Music app now allows upto 10 minutes youtube links",""},
                {"> [Feature] All DX messages now output to console too (Press ~ to see)",""},
                {"> [Change] Lotto changed to #'s 1-30",""},
                {"> [Bug-Fix] One of the scripts that caused FPS loss fixed",""},
                {"> [Bug-Fix] Radio in Phone fixed!",""},
                {"> [Bug-Fix] Respawn @ Hospital, bug fix (you wont get stuck new)",""},
            }
        },
        {202,"v.1.5.3","February 9th, 2013",
            {
                {"> [Feature] House rob enabled and score added to it",""},
                {"> [Feature] Added setting to toggle support chat in phone","[CSG]Priyen"},
                {"     We do not encourage this, but sometimes there is too much",""},
                {"     going on in support chat",""},
                {"> [Feature] MF now get alerated when there is hostile aircraft presence","[CSG]Smith"},
                {"> [Feature] CRIMS: Precious car needs to be stolen! Deliver it for $$$","Prime"},
                {"> [Feature] LAWS: Stolen car needs to be recovered! Recover it for $$$",""},
                {"> [Feature] Added ' See Killcam ' to settings app in Phone","[CSG]Priyen"},
                {"> [Feature] Added ADS to LV Hospital Spawn -- ingame content",""},
                {"> [Bug-Fix] Houses system bug where you can SELL someone else's house","[CSG]Priyen"},
                {"> [Bug-Fix] Houses system bug where you can bug sell for a lot of $$$",""},
                {"> (Any housing transactions from the bug have already been reveresed)",""},
                {"> [Bug-Fix] Jetpack in DS issue",""},
            }
        },
        {199,"v.1.5.2","February 6th, 2013",
            {
                {"> [Bug-Fix] You can't rob dead people now",""},
            }
        },
        {198,"v.1.5.1","February 5th, 2013",
            {
                {"> [Feature] Kill Cam Added! Soon to come a setting for it in phone","[CSG]Priyen"},
                {"> [Feature] Added back weapons! Feel like the master of weapons","[CSG]Priyen"},
                {"     Phone > Back Weapon App > Pick your weapons",""},
                {"      Primary shows when the weapon is not in use, otherwise secondary",""},
                {"      Not all skins are calibrated / positioned correctly, but",""},
                {"      this will be fixed over a few days",""},
            }
        },
        {196,"v.1.5.0","February 3rd, 2013",
            {
                {"> [Feature] Hospital health / medical assistance pickups","Prime"},
                {"> [Bug-Fix] You can no longer fix your vehicle while doing driving test","[CSG]Priyen"},
                {"> [Feature] More Job Locations for Maps App in Phone","[CSG]Priyen"},
                {">     Thank You to [CSG]Tzeik for all the positions / data",""},
                {"> [Bug-Fix] You won't get wanted in event dimensions","[CSG]Priyen"},
                {"> [Bug-Fix] Bank Rob / CR related bugs (door, timer, death) fixed","[CSG]Priyen"},
                {"> [Feature] Fisherman > Sell All button","[CSG]Priyen"},
                {"> [Feature] You get 5 times LESS wanted points in LV","[CSG]Priyen"},
                {"  Law Salary for arresting also increased to offset / balance",""},
                {"> [Feature] New Tazer, one you can actually escape from!","[CSG]Priyen"},
                {"> [Feature] Wanted System toughned in LV for trollers.","[CSG]Priyen"},
                {"  Law attacking criminals in LV in attempt to get them to get wanted",""},
                {"  Will notice the difference",""},
                {"> [Notif.] Monster Build Status: 25% ","[CSG]Jack"},
                {">     Mainly Jack so far working on it",""},
                {"> [Feature] Music App in Phone!","[CSG]Priyen"},
                {">    Ever wanted to play music but was enable to?",""},
                {">    Always had to go convert it and upload, .mp3 etc?",""},
                {">    CSG's latest edition brings you the ability to",""},
                {">         *Play Youtube Links! (YES, no work on your part)",""},
                {">          eg. http://www.youtube.com/watch?v=Q6IoKnPERrQ",""},
                {">          It will even get the title for you!",""},
                {">         *All other standard MTA file types",""},
                {">         *Play music in a vehicle, if your the driver",""},
                {">         *Vehicle music HUD + Sync",""},
                {">         * Eg. when someone enters your vehicle, they hear",""},
                {">           the song from where it really is, not the beginning",""},
            }
        },
        {189,"v.1.4.9","February 1st, 2013",
            {
                {"> [Feature] All animations now have commands, type /animation name","[CSG]Priyen"},
                {">     /stopanim to stop doing an animation.",""}
            }
        },
        {188,"v.1.4.8","January 31st, 2013",
            {
                {"> [Feature] Premium custom hats feature!","Prime"},
                {">     Many cool hats for you to wear!",""},
                {">     /premhat to wear a hat and remove it",""},
            }
        },
        {187,"v.1.4.7","January 30th, 2013",
            {
                {"> [Bug-Fix] Wanted jacking bug in seasparrow fixed","[CSG]Priyen"},
                {"> [Bug-Fix] On reconnect Assassin skill loss fixed","[CSG]Priyen"},
                {"> [Bug-Fix] Weapons skills fixed for all players","[CSG]Priyen"},
                {">     If your fps was over 70, your skills were bugged, now fixed",""},
                {"> [Bug-Fix] Abusable tazer animation bug fixed","[CSG]Priyen"},
                {"> [Feature] Law Computer now has team based color coding","[CSG]Priyen"},
                {">     for all players that are blipped / marked",""},
                {"> [Feature] Law Computer now shows if a wanted player is in jail","[CSG]Priyen"},
                {"> [Feature] Added /togglepchat to enabled and disable premium chat","[CSG]Priyen"},
                {"> [Bug-Fix] Law Computer blip related problems fixed","[CSG]Priyen"},
                {"> [Bug-Fix] When you get 3 stars, you turn criminal + get your skin back","[CSG]Priyen"},
                {"> [Feature] Drug Commands (bindable)",""},
                {">     /takehit name amount",""},
                {">     Amount is automatically 1 if not specified",""},

            }
        },
        {184,"v.1.4.6","January 28th, 2013",
            {
                {"> [Feature] Math Task!","[CSG]Smith"},
                {">     Can you do the math?",""},
                {"> [Feature] Bike Skills!","[CSG]Smith"},
                {">     Upgrade your bike skills as you gain experience",""},
            }
        },
        {183,"v.1.4.5","January 26th, 2013",
            {
                {"> [Feature] Food / Restaurant drive thru's!","Brad"},
                {"> [Bug-Fix] Help messages at top accelertad when there is a lot showing","[CSG]Priyen"},
                {">     (Anti-help spam + Bus driver spam fix)",""},
                {"> [Feature] Drug timers added!","[CSG]Priyen"},
                {">     Phone > Settings > 'See drug timers' to toggle",""},
                {"> [Feature] Drug system changed a little, hits stackable","[CSG]Priyen"},
                {">     (But not infintely)",""},
                {"> [Feature] You now get 0.5 score for killing someone","[CSG]Priyen"},
                {">     (But they still lose 1)",""},
                {"> [Bug-Fix] Mechanic damage proof bug fixed","[CSG]Priyen"},
                {"> [Bug-Fix] Law arresting bug fixed (some law couldn't arrest)","[CSG]Priyen"},
                {"> [Bug-Fix] Drug Shipment jetpack bug fixed","[CSG]Priyen"},
                {"> [Bug-Fix] You can now recover vehicles in water regardless of distance","[CSG]Priyen"},
                {"> [Bug-Fix] Ferrari's Handling fixed and optimized by Kirito",""},
            }
        },
        {179,"v.1.4.4","January 25th, 2013",
            {
                {"> [Feature] Pilot Job now gives score!","[CSG]Priyen"},
                {"> [Feature] Added command /drugs for those with bind problems","[CSG]Priyen"},
                {"> [Change] Score requirements for LAW Skills are now half!","[CSG]Priyen"},
                {"> [Bug-Fix] Pilot Job ranks fixed","[CSG]Priyen"},
                {"> [Bug-Fix] Blank ranks in Tab / Scoreboard","[CSG]Priyen"},
                {"> [Bug-Fix] You couldn't re-enter vehicles with wanted star","[CSG]Priyen"},
                --{"> [Bug-Fix] You no longer get wanted for damaging your own car","[CSG]Priyen"},
                {"> [Bug-Fix] All PD's now have the law skills markers","[CSG]Priyen"},
                {"> [Bug-Fix] Added criminal markers job descriptions","[CSG]Priyen"},
            }
        },
        {178,"v.1.4.3","January 23rd, 2013",
            {
                {"> [Feature] New Tazer Effect","[CSG]Priyen"},
                {"> [Bug-Fix] You can no longer turf in air vehicles","[CSG]Priyen"},
                {"> [Bug-Fix] You no longer get wanted for damaging your own car","[CSG]Priyen"},
                {">     (Both Job and Owned Vehicles)",""},
                {">     Unless the damage causes someone to die..",""},
                {"> [Feature] You no longer lose score for deaths IF,","[CSG]Priyen"},
                {">     You died in the main interior but a different dimension",""},
                {">     You were killed by a staff member",""},
                {"> [Feature] Old tazer added back, new removed.","[CSG]Priyen"},
                {"> [Feature] New Ferrari Model","[CSG]Priyen"},
                {">     Handling will be fixed soon",""},
                {"> [Bug-Fix] House Weapon's Storage enabled again","[CSG]Priyen"},
            }
        },
        {176,"v.1.4.2","January 21st, 2013",
            {
                {"> [Bug-Fix] Anti-weapon training abuse, made by Sathler",""},
                {"> [Bug-Fix] Sometimes criminal ranks don't show in tab fixed","[CSG]Priyen"},
                {"> [Feature] A new tazer! (new animations for gun and being tazerd)","[CSG]Priyen"},
                {"> [Feature] All players are now visible by default","[CSG]Priyen"},
                {">     Uncheck Phone > settings > 'See all players' for old system",""},

                {"> [Feature] Ferrari added to vehicle shops","[CSG]Sensei"},
                {">           $2 Million, Max Speed 341 Km/h",""},


                {"> [Bug-Fix] Cops getting wanted for jacking a criminal fixed","[CSG]Priyen"},
                {"> [Bug-Fix] 'Casino markers on roof bug fixed'","[CSG]Priyen"},
                {"> House Weapons Storage disabled for 24 hours!",""},
                {">           Don't worry, you will NOT lose anything inside.",""},
                {"> [Bug-Fix] 'Your wanted level is too high bug'","[CSG]Priyen"},
                {"> [Bug-Fix] Group banking transactions log fixed","[CSG]Priyen"},
                {"> [Bug-Fix] You can't deposit $0 or less in group bank","[CSG]Priyen"},
            }
        },
        {172,"v.1.4.1","January 19th, 2013",
            {
            {"> [Change]  New payments and score tables for some jobs","HBK"},
            {">           In attempt to balance job salaries + score",""},
            {">           Paramedic, Electrician, and Trash Collector",""},
            --{"> [Change]  Weapons Training now gives 10% instead of 5%",""},
            {"> [Bug-Fix] House System (ALL STORAGES FIXED)","[CSG]Priyen"},
            {"> [Bug-Fix] You can't pickup flag now while arrested","[CSG]Priyen"},
            {"> [Feature] Barriers, Rewrited, added Dx Message on Spawn,","[CSG]Smith"},
            {"            added /flare, removed barrier4 as it same #1",""},
            {"> [Feature] Portguese translation (full) for F1 added!","[CSG]Priyen"},
            {"           > Full Translation provided by (Sathler)! (All Tabs)",""},
            {"> [Feature] First Person view Mode added","[CSG]Priyen"},
            {"           > Press 'V' to toggle your view modes!",""},
            {"           > Works in vehicles and onfoot",""},
            {"> [Feature] You now get score for training your weapons!","[CSG]Smith"},
            {"> [Feature] You can now spawn free-vehicles with upto 1 wanted star","[CSG]Priyen"},
            {"> [Bug-Fix] Abusable score bugged fixed in store robberies","[CSG]Priyen"},
            {"           > Now the score given is based on how much you rob",""},
            {"> [Bug-Fix] Buying food will actually now increase your HP past 100","[CSG]Priyen"},
            {"           > (If your on drugs)",""},
            {"> [Bug-Fix] You now can't get pickups when using jetpack","[CSG]Priyen"},
            {"> [Bug-Fix] Turf Respawn glitches fixed","[CSG]Priyen"},
            {"> [Bug-Fix] Emergency Signal Lights disabled for non-Emergency vehicles","[CSG]Priyen"},
            {"> [Bug-Fix] Most Bad Interiors Fixed (eg. Water in interior)","[CSG]Priyen"},
            {"> [Change] Vehicle Recovery distance increased","[CSG]Priyen"},

            }
        },
        {162,"v.1.4.0","January 16th, 2013",
            {
                {"> [Feature] Bank Rob has been added back!",""},
                {"           > /banktime /casinotime",""},
                {"> [Bug-Fix] You no longer respawn in the sea when you die near jail",""},
                {"> [Feature] PT/BR Chat Added to the chat system!",""},
                {"           > /pt msg, /br msg, OR 'J' chat room",""},
                {"> [Notif.] Jail Preview Topic on FORUM has been updated",""},
            }
        },
        {161,"v.1.3.9","January 15th, 2013",
            {
                {"> [Bug-Fix] Casino Robbery Door will now, automatically open.","[CSG]Priyen"},
                {"> [Bug-Fix] You can no longer recover a car while arrested or jailed",""},
                {"> [Bug-Fix] You can no longer recover a car while your driving it..",""},
                {"> [Bug-Fix] Jail Timer Bug, since  we don't know how to reproduce,",""},
                {"           > Please tell an admin if you still get the bug",""},
                {"> [Change] You can now only get pickups (eg. armor) once per 60 seconds",""},
                {"> [Bug-Fix] A problem with gates opening and closing",""},
            }
        },
        {158,"v.1.3.8","January 13th, 2013",
            {
                {"> [Feature] Job Descriptions for MOST Jobs) ","HBK"},
                {"> [Preview] CSG's New Federal Prison is nearly open to new convicts.) ","[CSG]Priyen"},
            }
        },
        {157,"v.1.3.7","January 11th, 2013",
            {
                {"> [Change] Explosives and Jetpack disabled in Drug Shipment Area","[CSG]Bibou"},
                {"> [Notif.] Anti-Lag Measures Added to current scripts. ","[CSG]Priyen"},
                {"           > Packet Loss decreased nearly 10 times.",""},
                {"           > You should no longer get 'random' network troubles.",""},
                {"           > If you still lag, consider your internet connection first",""},
                {"           > The chance of server causing your lag is now near impossible.",""},
            }
        },
        {155,"v.1.3.6","January 10th, 2013",
            {
                {"> [Feature] Law Skills Added!) ","[CSG]Priyen"},
                {"           > Regular Officer, Drug Squad, Support Unit",""},
                {"           > Explosives Unit, Bomb Squad, The Tank",""},
                {"           > Task Force, Range Unit, Riot Squad, the Mechanic",""},
                {"           > High Speed Unit (not enabled)",""},
                {" Please report bugs, if any to the appropriate section on csgmta.net",""},
                {"> [Change] Fire Fighter fire no longer damages you or your vehicle.",""},
            }
        },
        {154,"v.1.3.5","January 9th, 2012",
            {
                {"> [Update/Notif.] 10 / 12 of the Law Skills are completed.",""},
                {"  ALL beind added in-game on January 10th, 2012",""},
                {"> 1 day delay due to new skill > 'Mechanic'",""},
                {"> [Feature] Additional SWAT Team skin added (now total becomes 2 skins) ",""},
                {"> [Feature] New Premium Skin 'The Rabbit' has been added to the clothes shop.",""},
                {"           > Made by our very own member, Rabbit",""},
                {"> [Feature] Skin 299, Claude, has been updated to GTA3 style",""},
                {"           > Thank You to Thomas for the neccesary stuff",""},
            }
        },
        {153,"v.1.3.4","January 8th, 2013",
            {
                {"> [Feature] Updated, better looking SWAT,MF,FBI car logo's","[CSG]Sensei"},
                {"> [Feature] Car Inventory (for LAW only). Normal cop cars spawn with","[CSG]Priyen"},
                {"  pilon,barriers,stinger,etc, depending on if your normal or official law",""},
            }
        },
        {152,"v.1.3.3","January 6th, 2013",
            {
                {"> [Update/Notif.] Law Skills (similiar to Criminal Skills) Officially being",""},
                {"  added ON or BEFORE January 9th 2012",""},
                {"> [Update/Notif.] New /store design coming soon",""},
                {"> [Change] Your jail time is now HALF, if most of your crimes were in LV",""},
                {"> [Bug-Fix] Turf respawn falling underground fixed","[CSG]Priyen"},
                {"> [Bug-Fix] Occassion bad camera spawn positioning fixed","[CSG]Priyen"},
                {"> [Feature] Credits Update (V3)","[CSG]Jack"},
                {"           > Stability fixes",""},
                {"           > New support for external purchases",""},
                {"> [Bug-Fix] Some false walls fixes added","Sathler"},
                {"> [Bug-Fix] Recover related bugs for vehicle system fixed","[CSG]Priyen"},
            }
        },
        {151,"v.1.3.2","January 5th, 2013",
            {
                {"> [Feature] Street Cleaner Job Added (SCORE enabled Job)","[CSG]Priyen"},
                {"> [Feature] Waste Collector Job + Score with it added","[CSG]Jack+Priyen"},
            }
        },
        {149,"v.1.3.1","January 4th, 2013",
            {

                {"> [Feature] commands /set(swat/mf/fbi)job and /rev(swat/mf/fbi)job Done.","[CSG]Smith"},
                {"           > Updated and fixed",""},
                {"> [Change] Store no longer on cache load, direct load from DB","[CSG]Jack"},
                {"           > Credits no longer on a cache load, direct load from DB",""},
                {"> [Feature] Updated Phone, Settings and Job calls","[CSG]FabioGNR"},
                {"> [Feature] Drugs Selling Added, use /selldrugs","[CSG]Priyen"},
                {"> [Feature] Realistic Clouds","[CSG]Jack"},
            }
        },
        {148,"v.1.3.0","January 2nd, 2013",
            {
                {"> [Feature] New Vehicle Shops!","[CSG]FabioGNR"},
                {"           > Choose license plates",""},
                {"           > Test drive before you buy!",""},
                {"> [Feature] New vehicle system with additional features","[CSG]Priyen"},
                {"> [Feature] Credits System added (V2)","[CSG]Jack"},
                {"           > Store system now in a stable state to release ",""},
                {"           > Management system finished ",""},
                {"           > Store management system (50% done) ",""},
                {"> [Bug-Fix] Jail related bugs fixed","[CSG]Priyen"},
                {"> [Bug-Fix] Score related bugs fixed","[CSG]Priyen"},
                {"> [Feature] New vehicle HUD","[CSG]Fabio"},
                {"           > New speedometer, health bar, gps!",""},
                {"> [Feature] Choose where you want to continue your life..respawn","[CSG]Priyen"},
                {"           > Criminals - Hospital or Turf (forced turf if wanted)",""},
                {"           > Law Groups - Hospital or Base ",""},
                {"           > Civilians / anyone else - Hospital ",""},
                {"> [Bug-Fix] Fixed a bug with the patrol mission markers","[CSG]Priyen"},
                {"> [Bug-Fix] Turfing number rounding","[CSG]Priyen"},
                {"> [Bug-Fix] Turfing interior / dimension bug","[CSG]Priyen"},
            --  {"> [Change] Added SWAT Job description",""},
            }
        },
        {144,"v.1.2.9","December 31st, 2012",
            {
                {"> [Feature] You can now transfer money to other's bank accounts via ATM's","[CSG]Jack+Priyen"},
                {"> [Feature]  /setmfjob , /setswatjob and /setfbijob added for leaders of current team","[CSG]Smith"},
                {"> [Bug-Fix] Weapon LOSS - PERMENANTLY FIXED.","[CSG]Priyen"},
                {"> [Feature] *Unread Messages for Phone* ","[CSG]Fabio"},
                {"           > See messages you haven't seen!",""},
                {"> [Feature] Calculator app for Phone* ","[CSG]Fabio"},
                {"           > Those times when you need to calculate...",""},
                {"> [Bug-Fix] All house-permission related problems fixed!","[CSG]Priyen"},
                {"           > Specifically those with ENTER House issues, this is now fixed!",""},
                {"> [Feature] New better respawn system","[CSG]Priyen"},
                {"           > See an ambulance take you to the hospital!",""},
                {"           > Spawn to the hospital thats actually near you!",""},
                {"           > Eg. In a LS interior in LV? no problem! Youll be taken to",""},
                {"           > LV General Hospital, not LS!",""},
                {"> [Temporary Change] Don of LV and Capo are now enabled again!","[CSG]Priyen"},

            }
        },
        {142,"v.1.2.8","December 30th, 2012",
            {
                {"> [Bug-Fix] Weapon Skills - PERMENANTLY FIXED.","[CSG]Priyen"},
                {"> [Temporary Change] Don of LV and Capo still disabled for 12 more hours","[CSG]Priyen"},
                {"> [Bug-Fix] Multiple people can now train their weapons at the same time","[CSG]Priyen"},
                {"> [Feature] New Turfing System! [Law Turfing]","[CSG]Priyen"},
                {"           > 4 Law-enabled Turfs, each has a radio tower",""},
                {"> When law owns a radio tower turf, you WILL get wanted",""},
                {"  for crimes in that zone.",""},
                {"> When criminals owns a radio tower turf, you will NOT ",""},
                {"  get wanted for crimes in that zone..",""},
                {"> When radio tower turf is neutral, 50% chance of getting wanted",""},
                {"  in that zone."},
                {"> Zone based on nearest radio tower to you in LV",""},
                {"> Criminals,staff,Law see radar blips at all times",""},
                {"> Others, only in LV",""},
            }
        },
        {140,"v.1.2.7","December 29th, 2012",
            {
                {"> [Temporary Change] Don of LV and Capo disabled for 24 hours","[CSG]Priyen"},
                {"                    > Mainly to adjust for the new turfing system.",""},
                {"> [Feature] New Turfing System!","[CSG]Priyen"},
                {"           > Group Influence",""},
                {"           > The more members of your group in a turf, the faster you can take it.",""},
                {"           > You can now 'defend' with reason, get paid in money and score",""},
                {"           > Law Enforcement Turfs [4] -- Each @ Radio Stations",""},
                {"                    > LAW TURFING being Added prior to, OR ON December 30th 2012",""},
                {" * Report ALL BUGS, if any, of the new turfing system on the forum!",""},
                {" If abusable / major, report only to admins via sms or private message",""},
            }
        },
        {139,"v.1.2.6","December 28th, 2012",
            {
                {"> [Feature] Police Cars for SWAT,MF,FBI have their logos on them!","[CSG]Priyen"},
                {"           > Thank You to Arkeo and Gusolina for help",""},
                {"> [Feature] Pilot job Tug Spawners added!","[CSG]Priyen"},
                {"> [Bug-Fix] You can no longer warp to an event while jailed","[CSG]Bibou"},
                {"> [Bug-Fix] Added staircase to get in / out of the north east LV Turf","[CSG]Priyen"},

            },
        },
        {137,"v.1.2.5","December 26th, 2012",
            {
                {"> [Bug-Fix] Laser is no longer infinite!","[CSG]Priyen"},
                {"           > When Laser battery is done, it will not work anymore",""},
                {"           > Color will now stay! It will not reset to red if you reconnect.",""},
                {"> [Feature] Houses App! N > Phone > Houses to see your houses!","[CSG]Priyen"},
                {"> [Feature] Police Emergency Head Lights!",""},
                {"> [Feature] Barriers added for SWAT (same as MF)","[CSG]Smith"},
                {"> [Feature] Bribe for FBI","[CSG]Priyen"},
                {"> [Bug-Fix] Casino Rob's door fixed! + the money rates for it too","[CSG]Priyen"},
                {"> [Bug-Fix] Your now auto-released when a cop accepts your bribe","[CSG]Priyen"},
            }
        },
        {134,"v.1.2.4","December 24th, 2012",
            {
                {"> [Feature] Official Law Chat added! use /smf msg ","[CSG]Bibou"},
            }
        },
        {133,"v.1.2.3","December 23rd, 2012",
            {
                {"> [Feature] Lottery changed to 1-50 instead of 1-100",""},
                {"           > Changed it's advert to dx Messages",""},
                {"> [Feature] Added barriers and lift for MF!","[CSG]Smith"},
                {"           > /barrier1-4",""},
                {"           > Example, /barrier1 ",""},
                {"           > /destroyall",""},
                {"> [Feature] Gas Masks for MF and SWAT added!","[CSG]Smith"},
                {"> [Bug-Fix] Staff can't be stealth killed now!","[CSG]Smith"},
                {"> [Feature] Fixed Event Panel + new one","[CSG]Bibou"},
                {"> [Feature] Drug Shipment added, use /drugtime","[CSG]Priyen"},
                {"> [Feature] New Dx Messages!","[CSG]Priyen"},
                {"> [Feature] ATM System Updated","[CSG]Jack"},
                {"           > New GUI Layout",""},
                {"> [Feature] Max Robbery Limits Changed;","[CSG]Priyen"},
                {"    > Max 60k --There is banks..storages for a reason.",""},
                {"    > You can no longer ROB anyone in Casino Rob",""},
                {"    > Post in Server Development concerns or opinions",""},
                {"> [Feature] Assassin Criminal Skill disabled in CR;","[CSG]Priyen"},
                {"           > Will be disabled in Drug Shipment",""},
            }
        },
        {126,"v.1.2.2","December 21st, 2012",
            {
            {"> [Feature] Event Panel / Events fixed! (admins can do events now!)","[CSG]Priyen"},
            {"> [Feature] Sell your house to the bank for 75% of its market value!","[CSG]Priyen"},
            {"> [Feature] New Turfs for LV","[CSG]Priyen"},
            {"           > 2 @ Bottom Left LV",""},
            {"           > 1 @ Top Right LV",""},
            {"           > 1 @ Top Left LV",""},
            }
        },
        {123,"v.1.2.1","December 19th, 2012",
            {
            {"> [Feature] Casino Robbery now 1 hour and 10 minutes only!","[CSG]Priyen"},
            {"           > 4k for killing criminal + score!",""},
            {"           > 2k for killing law + score!",""},
            {"           > 18k for successfull rob + score!",""},
            {"> [Bug-Fix] Assassin and Butcher skills fixed","[CSG]Priyen"},
            {"> [Bug-Fix] You can no longer /kill in jail","[CSG]Priyen"},
            }
        },
        {122,"V 1.2.0","December 15th, 2012",
            {
            {"*** Anything showing ==> 'December 16th, 2012' will be added tomorrow",""},
            {"*** Final testing",""},
            {"> [Bug-Fix] You can now actually move+shoot at max weapon skill! Fixed!","[CSG]Priyen"},
            {"> [Feature] Car Crash! A car crash will force the fire department to save you!","[CSG]Smart"},
            {"> [Feature] You like killing people ehh? hitman is perfect for you! Kill the hit!","[CSG]Smart"},
            {"> [Feature] Score System (use to unlock new things!)","[CSG]Jack"},
            {"> [Feature] New Bank Rob ==> December 16th, 2012","[CSG]Psydomin"},
            {"> [Feature] Drug Shipment ==> December 16th, 2012","[CSG]Priyen"},
            {"> [Feature] Over 50 Daily and Weekly Statistics [GAME TIME]","[CSG]Priyen"},
            {"           > Player records...etc",""},
            {"> [Feature] Updated F1",""},
            {"> [Feature] Arrest Assist payments","[CSG]Smart"},
            {"> [Feature] Lasers [buy at ammunation] ==> December 16th, 2012",""},
            {"> [Feature] New Criminal 'Jobs'","[CSG]Priyen"},
            {"           > Don of LV",""},
            {"           > Drug Smuggler",""},
            {"           > Assassin",""},
            {"           > Butcher",""},
            {"           > Con Artist",""},
            {"           > Pick Pocket",""},
            {"           > Burgler",""},
            {"           > Capo",""},
            {"           > Smooth Talker",""},
            {"           > Petty Criminal",""},
            {"> [Feature] Peak System","[CSG]Jack"},
            {"> [Feature] Upgraded House System","[CSG]Priyen"},
            {"> [Feature] Lottery! /lotto num","[CSG]Priyen"},
            {"> [Feature] Police Ranks","[CSG]Priyen"},
            }
        },
        {115,"v 1.1.0","December 8th, 2012",
            {
                {"> [Bug-Fix] You will be released when a law accepts your bribe now!","[CSG]Priyen"},
                {"> [Bug-Fix] Fixed 24-7 shops, now you can buy the items! ","[CSG]Priyen"},
                {"> [Bug-Fix] Fixed veh engine,type /engine to toggle engine now ","[CSG]Priyen"},
                {"> [Feature] Patrol Mission no longer has a limit!","[CSG]Priyen"},
                {"> [Feature] Barriers for SWAT Team Added!","[CSG]Psydomin"},
                {"            > Press X at the trunk of a valid vehicle",""},
                {"> [Feature] New Store Robberies","[CSG]Priyen"},
                {"            > /holdup or /robstore to rob a store",""},
                {"> [Feature] LAW can get crime reports!","[CSG]Priyen"},
                {"            > /respond ID to respond to a report",""},
                {"            > /rescancel to stop Responding",""},
                {"> [Feature] Staff Panel warp player to, now works!","[CSG]Jack"},
                {"> [Bug-Fix] AFK+reconnect spawns you in wrong dimension, fixed!","[CSG]Jack"},
                {"> [Bug-Fix] Gym marker shows in all interiors, fixed!","[CSG]Psydomin"},
                {"> [Bug-Fix] Staff panel health+armor rounding bug, fixed!","[CSG]Jack"},
                {"> [Bug-Fix] Ability to shoot + aim in drug factory, fixed!","[CSG]Jack"},
                {"> [Bug-Fix] HP loss in jail, fixed!","[CSG]Jack"},
                {"> [Bug-Fix] Limit ATM marker height, fixed!","[CSG]Jack"},
            }
        },
        {110,"v 1.0.3","December 6th, 2012",
            {
                {"> [Feature] New Updates System. To keep you upto date and aware!","[CSG]Priyen"},
                {"            > Will be added to [F1] - Help Menu soon",""},
                {"            > [F1] - Help Menu will also be updated soon",""},
                {"> [Feature] New Wanted Detection System, get jailed to see, /crimes","[CSG]Priyen"},
                {"            > If you find bugs please report on CSG forum",""},
                {"> [Feature] Police Patrol Mission - Updated","[CSG]Priyen"},
                {"            > Now has different crime committers!",""},
                {"> [Bug-Fix] You now only lose stars when there is no LAW nearby","[CSG]Priyen"},
                --{"> [Feature] The next time I relog, only new will be green.","[CSG]Priyen"}}
            },
        },
        {109,"v 1.0.2","December 2nd, 2012",
            {
                {"> [Feature] New Vehicle System.","Dennis"},
                {"            > Recover fixed, can spawn 2 cars, new gui",""},
                {"            > Now see location and health w/ color",""},
                {"> [Feature] > Added fuel points for boats, planes","Dennis"},
                {"> [Bug-Fix] > Disabled fuel decreasing for bicycles","Dennis"},
            }
        }
    }
